[package]
name = "rust2srs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.2"
ffmpeg-next = "6.0.0"
jpeg-encoder = "0.5.1"
pest = "2.7.3"
pest_derive = "2.7.3"
